#392201: Logo alignment
bsi-software/bsi-cx-design-master-template-email pull request #46
Opened 2024-08-15 13:37 UTC by derB4

2024-08-19 06:32 UTC, innerjoin requested changes
Super, dass wir das angehen. Hat mich letzthin auch genervt :-)

2024-08-19 06:32 UTC, innerjoin commented on templates/email/properties.js
> +  logoAlign: 'right',
Zwecks Rückwärtskompatibilität und weil die Mehrzahl der Logos (im Web, bei Mail weiss ich's nicht) links ausgerichtet ist, würde ich hier `left` als Standardwert wählen.

2024-08-28 08:26 UTC, LukasBSI approved these changes

2024-08-28 08:26 UTC, LukasBSI approved these changes

2024-08-28 10:45 UTC, innerjoin approved these changes

2024-08-28 10:45 UTC, merged